name: predict
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas==2.2.3
  - numpy==2.1.2
  - scikit-learn==1.5.2
  - matplotlib==3.9.2
  - scipy==1.14.1
  - joblib==1.4.2
  - xgboost==3.1.0
  - seaborn
