name: netstart
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - torch==1.12.1
  - numpy==1.23.5
  - pandas==2.0.3
  - tqdm==4.62.3
  - transformers==4.36.0
  - huggingface_hub>=0.20.3
  - biopython>=1.78
  - scikit-learn>=0.24.0
